In [2]:
import pandas as pd
import numpy as np

In [4]:
pd.read_csv('divorce.csv')drr

,Unnamed: 0,year,date,all_3544,HS_3544,SC_3544,BAp_3544,BAo_3544,GD_3544,poor_3544,...,rich_3544,all_4554,HS_4554,SC_4554,BAp_4554,BAo_4554,GD_4554,poor_4554,mid_4554,rich_4554
0,1,1960,1960-01-01,0.034445,0.034889,0.033669,0.027513,0.027513,NaN,0.071951,...,0.022562,0.039651,0.040071,0.038703,0.031886,0.031886,NaN,0.075373,0.029337,0.023505
1,2,1970,1970-01-01,0.049256,0.050000,0.048705,0.041259,0.041259,NaN,0.113736,...,0.021927,0.050626,0.050566,0.051473,0.048311,0.048311,NaN,0.112496,0.033869,0.021233
2,3,1980,1980-01-01,0.106005,0.104151,0.112699,0.097772,0.097772,NaN,0.241647,...,0.035015,0.088185,0.085664,0.095009,0.091035,0.091035,NaN,0.198673,0.063009,0.027916
3,4,1990,1990-01-01,0.150805,0.159381,0.169670,0.114955,0.118534,0.109145,0.326948,...,0.049725,0.145726,0.140779,0.166331,0.134370,0.135661,0.132741,0.306614,0.114981,0.045775
4,5,2000,2000-01-01,0.156841,0.175446,0.173803,0.105618,0.110540,0.095903,0.343089,...,0.049395,0.179581,0.184777,0.201104,0.149042,0.153693,0.142550,0.382135,0.142242,0.051525
5,6,2001,2001-01-01,0.157306,0.174116,0.178169,0.107039,0.111861,0.097197,0.342836,...,0.040574,0.182651,0.190237,0.205737,0.148632,0.153269,0.141745,0.390039,0.146513,0.045222
6,7,2002,2002-01-01,0.156508,0.174769,0.179294,0.103442,0.109690,0.090763,0.341088,...,0.038796,0.180650,0.192090,0.198048,0.146439,0.152888,0.136777,0.383795,0.146242,0.046089
7,8,2003,2003-01-01,0.153844,0.172545,0.176975,0.102550,0.110683,0.086385,0.333105,...,0.039262,0.184698,0.194891,0.206792,0.147350,0.151223,0.141439,0.391315,0.151240,0.042694
8,9,2004,2004-01-01,0.154841,0.177565,0.177080,0.100337,0.105990,0.089114,0.334328,...,0.036796,0.184111,0.193739,0.208312,0.145630,0.151841,0.135796,0.391199,0.150755,0.041060
9,10,2005,2005-01-01,0.152920,0.175164,0.176743,0.099481,0.107115,0.084992,0.329074,...,0.037071,0.184325,0.197213,0.205276,0.143482,0.147395,0.137305,0.389394,0.150802,0.042773
10,11,2006,2006-01-01,0.161890,0.189437,0.184121,0.103835,0.110858,0.090503,0.337167,...,0.057895,0.196150,0.210708,0.219401,0.150398,0.156880,0.139726,0.401970,0.159174,0.063530
11,12,2007,2007-01-01,0.160469,0.187216,0.184961,0.103929,0.111882,0.089050,0.335230,...,0.058169,0.194960,0.212744,0.216564,0.146597,0.153198,0.135541,0.406419,0.154821,0.063713
12,13,2008,2008-01-01,0.161159,0.188377,0.189450,0.102019,0.111153,0.085194,0.333739,...,0.060336,0.197631,0.216824,0.219635,0.146631,0.151388,0.138511,0.409125,0.156001,0.066710
13,14,2009,2009-01-01,0.160493,0.186988,0.190136,0.101943,0.111839,0.084393,0.330015,...,0.059975,0.197649,0.217975,0.219473,0.144457,0.149930,0.135111,0.406765,0.157969,0.067577
14,15,2010,2010-01-01,0.163651,0.189896,0.197269,0.103064,0.111632,0.088167,0.328724,...,0.057761,0.203510,0.224317,0.224462,0.150590,0.158164,0.137254,0.409801,0.167156,0.069695
15,16,2011,2011-01-01,0.166303,0.192399,0.200459,0.107761,0.117284,0.091883,0.329541,...,0.058814,0.203296,0.225632,0.224448,0.148751,0.155389,0.137036,0.407424,0.169007,0.067626
16,17,2012,2012-01-01,0.165486,0.190206,0.203176,0.107407,0.115292,0.094314,0.331560,...,0.056355,0.207389,0.228669,0.231817,0.152475,0.160083,0.139317,0.410069,0.174465,0.070381